services:
  execution-service:
    build:
      context: ./Execution_Service
      dockerfile: ./Dockerfile
    environment:
      - OTHENTIC_CLIENT_RPC_ADDRESS=http://${AGGREGATOR_HOST:-localhost}:8545
      - PRIVATE_KEY=${PRIVATE_KEY_PERFORMER}
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY}
    env_file:
      - .env
    ports:
      - "4003:4003"
    networks:
      - default 