services:
  attester:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [
      "run",
      "attester",
      "/ip4/${AGGREGATOR_HOST:-localhost}/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://${VALIDATION_SERVICE_HOST:-localhost}:${VALIDATION_SERVICE_PORT:-4002}",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER}
      - L1_CHAIN=${L1_CHAIN}
      - L2_CHAIN=${L2_CHAIN}
    networks:
      - default 