version: '3.8'

services:
  aggregator:
    image: ghcr.io/alexr-scrt/aggregator:latest
    container_name: aggregator
    restart: unless-stopped

    command: [
      "run",
      "aggregator",
      "--json-rpc",
      # "--internal-tasks"
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_AGGREGATOR}
      - L1_CHAIN=${L1_CHAIN}
      - L2_CHAIN=${L2_CHAIN}
    ports:
      - "8545:8545"
      - "9876:9876"
    networks:
      p2p:
        ipv4_address: 10.8.0.69

  attester-1:
    image: ghcr.io/alexr-scrt/attester-1:latest
    container_name: attester-1
    restart: unless-stopped
    
    command: [
      "run",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER1}
      - L1_CHAIN=${L1_CHAIN}
      - L2_CHAIN=${L2_CHAIN}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.2

  attester-2:
    image: ghcr.io/alexr-scrt/attester-2:latest
    container_name: attester-2
    restart: unless-stopped
    
    command: [
      "run",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER2}
      - L1_CHAIN=${L1_CHAIN}
      - L2_CHAIN=${L2_CHAIN}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.3

  attester-3:
    image: ghcr.io/alexr-scrt/attester-3:latest
    container_name: attester-3
    restart: unless-stopped
    
    command: [
      "run",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER3}
      - L1_CHAIN=${L1_CHAIN}
      - L2_CHAIN=${L2_CHAIN}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.4

  validation-service:
    image: ghcr.io/alexr-scrt/validation-service:latest
    container_name: validation-service
    restart: unless-stopped
    
    networks:
      p2p:
        ipv4_address: 10.8.0.42

  execution-service:
    image: ghcr.io/alexr-scrt/execution-service:latest
    container_name: execution-service
    restart: unless-stopped
    
    environment:
      - OTHENTIC_CLIENT_RPC_ADDRESS=http://10.8.0.69:8545
      - PRIVATE_KEY=${PRIVATE_KEY_PERFORMER}
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY}
    ports:
      - "4003:4003"
    networks:
      p2p:
        ipv4_address: 10.8.0.101

networks:
  p2p:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/16
         gateway: 10.8.0.1
